# dependabot for GitHub
# https://dependabot.com/docs/config-file/

version: 2

updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/Berlin"
    reviewers:
      - "finnge"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/Berlin"
    reviewers:
      - "finnge"

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "Europe/Berlin"
    reviewers:
      - "finnge"