
root: true

extends:
  - airbnb-base

env:
  browser: true
  commonjs: true
  es2020: true

parserOptions:
  ecmaVersion: 11

rules:
  import/extensions: [error, always, { ignorePackages: true }]

ignorePatterns:
  - "dist"
  - "!.eleventy.js"