version: '3.8'

services:
  jekyll:
    container_name: finngedrath.me
    image: jekyll/jekyll:4.0
    command: jekyll serve --watch --incremental
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll