name: finngedrath.me CI

on:
  push:
    paths:
      - '**/*.css'

jobs:
  coding-style:
    name: Coding Style
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout Code
        uses: actions/checkout@v2.3.4
      -
        name: Setup Node Environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 10
      -
        name: Cache node modules
        uses: actions/cache@v2.1.6
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      -
        name: Install node dependencies
        run: npm install -D
      -
        name: Check Linting for CSS Code
        run: npm run lint:style
        if: ${{ success() || failure() }}

  build:
    name: Building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
